<a href="https://colab.research.google.com/github/armnkumar321-spec/pythonclasses/blob/main/day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#-> NUMPY



In [ ]:
import numpy as np

In [ ]:
a = np.array([1,3,9,0,'hellow'])
print(a)

['1' '3' '9' '0' 'hellow']


In [ ]:
#question 1
np_array=np.array([3,3,3,3,3.3,'hello',False])
print(bool(np_array[-1]))
a=False
print(bool(a))

True
False


In [ ]:

a=np.zeros((2,3,4),dtype=int)
print(a)
print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [ ]:
a=np.empty(4,dtype=int)
print(a)

[4607182418800017408 4613937818241073152 4621256167635550208
 4609434218613702656]


In [ ]:
a=np.full(4,5,dtype=int)
print(a)

[5 5 5 5]


In [ ]:
a=np.arange(1,10,1,dtype=int)
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
a=np.linspace(1,10,5,dtype=int)
print(a)

[ 1  3  5  7 10]


In [ ]:


arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
],dtype=int)
print(arr)

print(arr.shape)
print(arr.size)


[[1 2 3]
 [4 5 6]]
(2, 3)
6


In [ ]:

a=np.random.randint(1,7,4)
print(a)


[1 5 1 2]


In [ ]:
a=np.random.choice([2,5,2,9],2)
print(a)


[2 9]


In [ ]:
a=np.random.randint(1,7,4)

b=np.random.randint(1,7,4)
print(a)
print(b)
print(a*2)
print(a+b)
print(a-b)
print(a/b)




[4 5 1 4]
[3 3 2 2]
[ 8 10  2  8]
[7 8 3 6]
[ 1  2 -1  2]
[1.33333333 1.66666667 0.5        2.        ]


In [ ]:
lst=[1,2,3,4,5]
lst2=[1,2,3,4,5]
print(lst+lst2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
a=np.random.randint(2,15,6)
print(a)

[ 3  5 14 14  3  3]


In [ ]:
a=np.random.randint(2,15,6)
print(a)
b=a.reshape((2,3))
print(b)

[ 2 14  7 11  8 14]
[[ 2 14  7]
 [11  8 14]]


In [ ]:
a=np.random.randint(2,15,6)
print(a)
b=a.reshape((2,3))
print(b)
c=b.transpose()
print(c)



[ 2  9  2  8 11 14]
[[ 2  9  2]
 [ 8 11 14]]
[[ 2  8]
 [ 9 11]
 [ 2 14]]


In [ ]:
a=np.random.randint(2,15,6)
b=np.random.randint(2,15,6)
c=np.concatenate((a,b))
print(c)

[ 3 11 12 10  7 13 10 10  2 13  3  3]


In [ ]:
a=np.random.randint(2,15,6)
b=np.random.randint(2,15,6)
c=np.concatenate((a,b))
print(c)
d=np.concatenate((a,b),axis=0)
print(d)


[ 4 14 11  3  5  7 10  8  5  3  3  2]
[ 4 14 11  3  5  7 10  8  5  3  3  2]


### Column-wise Concatenation Example

To concatenate arrays column-wise, you use `np.concatenate` and set the `axis` parameter to `1`. This means the arrays are joined side-by-side along the second dimension.

In [ ]:


a = np.array([[10, 20],
                    [30, 40]])

b = np.array([[50, 60],
                    [70, 80]])

print(a)
print(b)


c = np.concatenate((a,b), axis=1)

print(c)
d = np.concatenate((a,b), axis=0)
print(d)



[[10 20]
 [30 40]]
[[50 60]
 [70 80]]
[[10 20 50 60]
 [30 40 70 80]]
[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [ ]:
a=np.random.randint(2,15,6)
b=np.random.randint(1,19,6)
print(a)
print(b)
c=np.where(b>2,b,a)
print(c)
d=np.sort(c)
print(d)
e=np.sum(d)
print(e)
f=np.mean(d)
print(f)
g=np.std(d)
print(g)
h=np.min(d)
print(h)
i=np.max(d)
print(i)
j=np.median(d)
print(j)
k=np.unique(d)
print(k)
l=np.matmul(a,b)
print(l)




[ 5  9  3  9 10 14]
[ 5 18 16  3 18 11]
[ 5 18 16  3 18 11]
[ 3  5 11 16 18 18]
71
11.833333333333334
6.039223643997813
3
18
13.5
[ 3  5 11 16 18]
596


In [ ]:
import numpy as np
n=int(input("enter size"))
lst=[]
DAYS=['SUN','MON','TUE','WED','THU','FRI','SAT']
for i in range(n):
  score=int(input(f"enter score FOR THE {DAYS[i]}:"))
  lst.append(score)
# print(" scores:", lst)


player_scores = np.array(lst)
print("Player scores ", player_scores)

std_score=np.std(player_scores)
print("SD of the all scores :", std_score)

max_score=np.max(player_scores)
max_score_index = np.argmax(player_scores)
max_score_day = DAYS[max_score_index]
print(f"Max score is on {max_score_day}: {max_score}")

min_score=np.min(player_scores)
min_score_index=np.argmin(player_scores)
min_score_day=DAYS[min_score_index]
print(f"Min score is on {min_score_day}: {min_score}")

mean_score=np.mean(player_scores)
print("mean of scores : ",mean_score)

median_score=np.median(player_scores)

if median_score in player_scores:
    median_score_index = np.where(player_scores == median_score)[0][0]
    median_score_day = DAYS[median_score_index]
    print(f"Median score is on {median_score_day}: {median_score}")
else:
    print(f"Median score: {median_score} (This value is not present )3")

enter size7
enter score FOR THE SUN:1
enter score FOR THE MON:2
enter score FOR THE TUE:33
enter score FOR THE WED:4
enter score FOR THE THU:5
enter score FOR THE FRI:6
enter score FOR THE SAT:7
Player scores  [ 1  2 33  4  5  6  7]
SD of the all scores : 10.277774713488542
Max score is on TUE: 33
Min score is on SUN: 1
mean of scores :  8.285714285714286
Median score is on THU: 5.0


In [ ]:
player_scores = np.array(lst)
print("Player scores as NumPy array:", player_scores)

mean_score = np.mean(player_scores)
std_dev = np.std(player_scores)

print(f"Mean score: {mean_score:.2f}")
print(f"Standard deviation: {std_dev:.2f}")

In [ ]:
score=input().split()
print(score)
score=[int(x) for x in scores]
print(score)

In [ ]:
a=np.array([3,3,3,3])
b=a
b[0]=1
print(a,b)