<a href="https://colab.research.google.com/github/armnkumar321-spec/pythonclasses/blob/main/day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
matrix = np.random.randint(1, 91, size=(5, 5))
print(matrix)

[[49 52  7  2 82]
 [43 15 80 11 29]
 [37 33 30 78  6]
 [13 81 59 82 88]
 [53 61 39 27 51]]


In [15]:
matrix = np.random.randint(1, 91, size=(5, 5))
print(matrix)
row_means = np.mean(matrix, axis=1)
col_means = np.mean(matrix, axis=0)
print(row_means)
print(col_means)


matrix[matrix % 2 == 0] = -1
print(matrix)
sum_row=np.sum(matrix, axis=1)
print(sum_row)
sum_col=np.sum(matrix, axis=0)
print(sum_col)
count_negative=np.count_nonzero(matrix<0,axis=0)
print(count_negative)
count_col=np.sum(np.where(matrxi<))


[[44 89 10 10 10]
 [65 10 64 69 24]
 [55 41  8 30 75]
 [73 74  8 65 88]
 [21 35 54 18 81]]
[32.6 46.4 41.8 61.6 41.8]
[51.6 49.8 28.8 38.4 55.6]
[[-1 89 -1 -1 -1]
 [65 -1 -1 69 -1]
 [55 41 -1 -1 75]
 [73 -1 -1 65 -1]
 [21 35 -1 -1 81]]
[ 85 131 169 135 135]
[213 163  -5 131 153]
[1 2 5 3 3]


In [30]:
matrix_stock=np.random.randint(20,80,size=(5,5))
print(matrix_stock)
matrix_demand=np.random.randint(20,80,size=(5,5))
print(matrix_demand)

remaing_matrix_stock=matrix_stock-matrix_demand
print(remaing_matrix_stock)
matrix_demand[remaing_matrix_stock<0]=0
print(matrix_demand)

total_shortaged_items=np.sum(remaing_matrix_stock<0,axis=0)
print(total_shortaged_items)
count_zeros=np.count_nonzero(matrix_demand==0,axis=0)
print(count_zeros)



remaing_stock_sorted=np.sort(remaing_matrix_stock)
print(remaing_stock_sorted)

[[65 57 62 63 63]
 [56 26 54 50 49]
 [21 64 66 35 59]
 [20 61 50 38 39]
 [59 70 67 38 26]]
[[79 78 54 27 71]
 [76 36 70 58 67]
 [68 68 20 39 75]
 [73 62 53 71 65]
 [25 55 75 39 47]]
[[-14 -21   8  36  -8]
 [-20 -10 -16  -8 -18]
 [-47  -4  46  -4 -16]
 [-53  -1  -3 -33 -26]
 [ 34  15  -8  -1 -21]]
[[ 0  0 54 27  0]
 [ 0  0  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0  0  0]
 [25 55  0  0  0]]
[4 4 3 4 5]
[4 4 3 4 5]
[[-21 -14  -8   8  36]
 [-20 -18 -16 -10  -8]
 [-47 -16  -4  -4  46]
 [-53 -33 -26  -3  -1]
 [-21  -8  -1  15  34]]


In [38]:
import pandas as pd
file_=pd.read_csv('student_data.csv')
print(file_.head())

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
